### ISSUE TITLE
Can't install the 1.5.1 via the Marketplace

### ISSUE THREAD

**Issue by kud** [jeff-hykin/better-shell-syntax#54]
```
2023-03-13 16:30:47.280 [error] PackageIntegrityCheckFailed: Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
```

**Comment by jeff-hykin** [comment]
Thats strange, I tested it on a secondary machine just now and it worked for me.

Was this output from installing it via the commandline?

**Comment by mrevjd** [comment]
I have the same issue when trying to update from within VSCode.
`2023-03-14 09:04:24.374 [error] Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-14 09:04:24.411 [error] PackageIntegrityCheckFailed: Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)`

**Comment by guzy0324** [comment]
the latest version can be installed manually by downloading and installing the vsix file.

**Comment by Akkowicz** [comment]
Same problem for me, Windows 11, latest VS Code.

**Comment by jeff-hykin** [comment]
Well this is bad. @alexr00 Any idea what might be going on?

Nothing has changed on my end, same publish command / token. The CLI command does take significantly longer than usual the last two times, but I get the same output as usual:

<img width="1274" alt="Screen Shot 2023-03-14 at 1 39 57 PM" src="https://user-images.githubusercontent.com/17692058/225105409-3790b7bd-087c-4d59-80a5-a17bcd5ae44b.png">

**Comment by alexr00** [comment]
It seems that in some cases signature verification is not working (ex. https://github.com/microsoft/vscode/issues/175733).

I've created https://github.com/microsoft/vscode/issues/175733 and the folks who know about extension signing are looking into it.

**Comment by kud** [comment]
`1.5.2` fixed it. Thank you.
